# Generated by Django 4.1.5 on 2023-02-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_myuser_plan_alter_job_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='fk',
            new_name='user',
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.myuser'),
            preserve_default=False,
        ),
    ]
