# Generated by Django 4.1.5 on 2023-02-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_job_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_is_paid',
            field=models.BooleanField(blank=True, default=False, max_length=255, null=True),
        ),
    ]
