# Generated by Django 4.1.5 on 2023-01-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_job_job_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_platform_id',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_category_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
