# Generated by Django 4.1.5 on 2023-01-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_job_job_platform_id_alter_job_job_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
