# Generated by Django 4.1.5 on 2023-01-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_job_job_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_start_date',
        ),
    ]
